name: Convert Jupyter Notebooks to HTML

on:
  push:
    branches: [main]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install nbconvert
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      - name: Find and Convert Notebooks
        run: |
          for notebook in $(find study1 -name "*.ipynb"); do
            jupyter nbconvert --to html "$notebook"
          done

      - name: Create docs directory if not exists
        run: mkdir -p docs

      - name: Move HTML files to docs
        run: |
          find study1 -name "*.html" -exec mv {} docs/ \;

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add docs/
          git commit -m "Add converted HTML files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
