name: Convert Jupyter Notebooks to HTML

on:
  push:
    branches: [main]

permissions:
  contents: write
      
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install nbconvert
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      - name: Convert Study 1 Questionnaires
        run: |
          cd content/study1/questionnaire
          jupyter nbconvert --to html study1_questionnaire.ipynb
          mv *.html ../../../docs/first-study
          cd ../../..

      - name: Convert Study 1 Experiments
        run: |
          cd content/study1/experiment
          jupyter nbconvert --to html study1_experiment.ipynb
          mv *.html ../../../docs/first-study
          cd ../../..

      - name: Convert Study 2 Questionnaires
        run: |
          cd content/study2/questionnaire
          jupyter nbconvert --to html study2_questionnaire.ipynb
          mv *.html ../../../docs/second-study
          cd ../../..
  
      - name: Convert Study 2 Experiments
        run: |
          cd content/study2/experiment
          jupyter nbconvert --to html study2_experiment.ipynb
          mv *.html ../../../docs/second-study
          cd ../../..
          
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
            
          # Add the changes to the docs/ folder
          git add docs/
          git commit -m "Add converted HTML files"
            
          # Set the remote URL to use the token for authentication
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
            
          # Fetch the latest changes from the gh-pages branch
          git fetch origin gh-pages
            
          # Checkout the gh-pages branch
          git checkout gh-pages
            
          # Merge changes from main into gh-pages (if needed)
          git merge origin/main --strategy-option=theirs
            
          # Push the changes to the gh-pages branch
          git push origin gh-pages
        
        
