name: Deploy GitHub Page with Colab Link

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write  # Add this line to grant the necessary permission

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Create HTML file with Colab link
        run: |
          mkdir -p public
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Study 1 Experiment</title>
          </head>
          <body>
            <h1>Study 1 Experiment</h1>
            <p>Access the interactive Jupyter Notebook on Google Colab:</p>
            <a href="https://colab.research.google.com/drive/1N_A4JoCns2JTmKqN9evrXcFwvGaMl7Ce?usp=sharing" target="_blank">
              <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
            </a>
          </body>
          </html>' > public/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.DEPLOYMENT_TOKEN }}


          